#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^\[[a-zA-Z0-9]*\-[0-9]*\] .*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<verb in imperative mood> <what was done>"
  echo "Format: ^\[[a-zA-Z0-9]*\-[0-9]*\] .*$"
  echo "Example: [LDS-123] add login button"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi
